### ISSUE TITLE
.NET Core 3.0 registration issues

### ISSUE THREAD

**Issue by mmbilinski** [khellang/Scrutor#105]
Hi. With the following code:

```csharp
services.Scan(scan => scan
    .FromExecutingAssembly()
    .FromApplicationDependencies()
        .AddClasses(c => c.AssignableTo<IProductRepository>(), true)
            .AsImplementedInterfaces()
            .WithTransientLifetime());
```

Scrutor crashes on startup with the following:

```
System.AggregateException:
---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Scrutor.MissingTypeRegistrationException Lifetime: Transient ImplementationType: Scrutor.MissingTypeRegistrationException': Unable to resolve service for type 'System.Type' while attempting to activate 'Scrutor.MissingTypeRegistrationException'. 
---> System.InvalidOperationException: Unable to resolve service for type 'System.Type' while attempting to activate 'Scrutor.MissingTypeRegistrationException'.
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
  --- End of inner exception stack trace ---
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
  at at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
  --- End of inner exception stack trace ---
  at at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
  at at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
  at at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
  at at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
  at at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
  at at Microsoft.Extensions.Hosting.HostBuilder.Build()
```

**Comment by khellang** [comment]
```csharp
services.Scan(scan => scan
    .FromExecutingAssembly() // <- This is probably your problem.
    .FromApplicationDependencies()
        .AddClasses(c => c.AssignableTo<IProductRepository>(), true)
            .AsImplementedInterfaces()
            .WithTransientLifetime());
```

If you don't specify `AddClasses`, it will automatically add *everything* in the source. The line above basically means "add all types in the executing assembly, registered as the type itself, with transient lifetime".

**Comment by mmbilinski** [comment]
In fact, I was able to remove FromExecutingAssembly() call completely and it's working now. Thank you!

**Comment by Maryam1986** [comment]
I had the same error when I replaced WebHostBuilder with HostBuilder in Program.cs and my problem solved with removing FromExecutingAssembly() line
Thanks

**Comment by Oxyrus** [comment]
Same, was having issues with it trying to inject values into my domain classes (such as integers). Solved it by removing `FromAssemblyOf<T>`

```csharp
builder.Services.Scan(scan => scan
    .FromApplicationDependencies()
        .AddClasses(classes => classes.AssignableTo<IScopedService>(), true)
            .AsImplementedInterfaces()
            .WithScopedLifetime()
);
```
