### ISSUE TITLE
Decorator - Could not find any registered services for type

### ISSUE THREAD

**Issue by gravity00** [khellang/Scrutor#26]
I'm creating a console application to make some tests using Scrutor to scan and decorate some command and event handlers. I'm facing a problem that, when I use the method `Decorate` it fails because it can't find any registered service for the type.

The example code is the following (also based on your tests):

```csharp
    public class Program
    {
        private readonly ILogger<Program> _logger;
        private readonly IMediator _mediator;

        public Program(ILogger<Program> logger, IMediator mediator)
        {
            _logger = logger;
            _mediator = mediator;
        }

        public static void Main(string[] args)
        {
            try
            {
                var services = new ServiceCollection()
                    .AddLogging()
                    /*
                    .Scan(s => s.FromAssemblyOf<Program>()
                        .AddClasses(classes => classes.AssignableTo(typeof(ICommandHandler<>)))
                        .AsImplementedInterfaces()
                        .WithScopedLifetime()
                        .AddClasses(classes => classes.AssignableTo(typeof(ICommandHandler<,>)))
                        .AsImplementedInterfaces()
                        .WithScopedLifetime()
                        .AddClasses(classes => classes.AssignableTo(typeof(IEventHandler<>)))
                        .AsImplementedInterfaces()
                        .WithScopedLifetime()
                        .AddClasses(classes => classes.AssignableTo<IUnitOfWork>())
                        .AsImplementedInterfaces()
                        .WithScopedLifetime())
                    //*/
                    .AddScoped<ICommandHandler<Example01Command, bool>, ExampleCommandHandler>()
                    .AddScoped<ICommandHandler<Example02Command>, ExampleCommandHandler>()
                    .AddScoped<ICommandHandler<Example03Command>, ExampleCommandHandler>()
                    .AddScoped<IEventHandler<ExampleEvent>, ExampleEventHandler>()
                    .AddScoped<IUnitOfWork, UnitOfWork>()

                    .AddSingleton<IMediator, Mediator>()
                    .AddSingleton<IHandlerFactory>(k => new DelegateHandlerFactory(k.GetService, k.GetServices))
                    .AddSingleton<Program>();

                //  EXCEPTION fails in this line, either registration by scan or manual
                services
                    .Decorate(typeof(ICommandHandler<>), typeof(AuditCommandHandler<>))
                    .Decorate(typeof(ICommandHandler<,>), typeof(AuditCommandHandler<,>))
                    .Decorate(typeof(IEventHandler<>), typeof(AuditEventHandler<>));

                var builder = new ContainerBuilder();
                builder.Populate(services);
                var serviceProvider = new AutofacServiceProvider(builder.Build());

                serviceProvider.GetRequiredService<ILoggerFactory>()
                    .AddConsole(LogLevel.Trace, true);

                serviceProvider.GetRequiredService<Program>()
                    .RunAsync(args, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }
            catch (Exception e)
            {
                Console.WriteLine("Global exception has been thrown");
                Console.WriteLine(e);
            }
            finally
            {
                Console.ReadLine();
            }
        }

        public async Task RunAsync(string[] args, CancellationToken ct)
        {
            _logger.LogInformation("Application started...");
            try
            {
                var result = await _mediator.PublishAsync<Example01Command, bool>(new Example01Command(), ct);

                _logger.LogDebug("Credential Login returned {credentialLoginResult}", result);
            }
            catch (Exception e)
            {
                _logger.LogCritical(0, e, "Global exception has been thrown");
            }
            finally
            {
                _logger.LogInformation("Application terminated. Press <enter> to exit...");
            }
        }
    }
```

The interfaces are as following (it's an internal library used by the company):

```csharp
public interface IEventHandler<in TEvent> where TEvent : IEvent
{
    // ...
}

public interface ICommandHandler<in TCommand> where TCommand : ICommand
{
    // ...
}

public interface ICommandHandler<in TCommand, TResult> where TCommand : ICommand<TResult>
{
    // ...
}
```

**Comment by khellang** [comment]
Which version is this?

**Comment by gravity00** [comment]
The test was using Scrutor version `1.12.0`.

I now made a test using version `2.0.0-rc` and the decorator fails with the following, as soon as the `Decorate` method is invoked:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at TestCommands.Program.Main(String[] args) in C:\Users\Joao.Simoes\documents\visual studio 2015\Projects\TestCommands\src\TestCommands\Program.cs:line 59
```

**Comment by khellang** [comment]
@gravity00 Pushed v2.0.0-rc2. It would be awesome if you could test it out and report back :smile:

**Comment by gravity00** [comment]
Ah, I was thinking version 1 already supported open generics.
Just made a test with version `2.0.0-rc2` and it fixed the problem. I even add more decorators to validate if all were invoked and the order was kept and everything looks ok:

```csharp
                services
                    .Decorate(typeof(ICommandHandler<>), typeof(AuditCommandHandler<>))
                    .Decorate(typeof(ICommandHandler<,>), typeof(AuditCommandHandler<,>))
                    .Decorate(typeof(IEventHandler<>), typeof(AuditEventHandler<>))
                    .Decorate(typeof(ICommandHandler<>), typeof(ValidateCommandHandler<>))
                    .Decorate(typeof(ICommandHandler<,>), typeof(ValidateCommandHandler<,>))
                    .Decorate(typeof(IEventHandler<>), typeof(ValidateEventHandler<>));
```

This week I'll make some tests in quality and staging environments using version `2.0.0-rc2` and if I find something odd I'll let you know.

**Comment by khellang** [comment]
@gravity00 Any feedback on this? Feel free to reopen if this is still a problem 😄

**Comment by gravity00** [comment]
@khellang no problem at all. Been using it is some of our production APIs and decorators have been working like a charm.

**Comment by khellang** [comment]
Good to hear! Rolled out 2.0 yesterday 😄

**Comment by khellang** [comment]
It's hard to tell based on your screenshot. Please open up a new issue with a repro and more details and I'll take a look at it ☺️
